openapi: "3.0.3"
info:
  title: YAB ?! Counts
  version: 1.0.2
  description: "Reimagining the concept of live counters."
servers:
  - url: https://api.yabcounts.com/public
security:
  - apiKey: []
paths:
  /youtube/channel/{channel_id}:
    get:
      summary: Get a YouTube channel
      parameters:
        - name: channel_id
          in: path
          required: true
          schema:
            type: string
            description: The ID of the YouTube channel.
          example: UCX6OQ3DkcsbYNE6H8uQQuVA
        - name: fields
          in: query
          required: false
          schema:
            type: string
            description: Used to specify the specific fields you want from the response.
          example: name,statistics.subscriberCount
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
                  handle:
                    type: string
                  url:
                    type: string
                  thumbnail:
                    type: string
                  banner:
                    type: string
                  statistics:
                    type: object
                    properties:
                      subscriberCount:
                        type: integer
                      publicSubscriberCount:
                        type: integer
                      viewCount:
                        type: integer
  /youtube/video/{video_id}:
    get:
      summary: Get a YouTube video
      parameters:
        - name: video_id
          in: path
          required: true
          schema:
            type: string
            description: The ID of the YouTube video.
          example: QjvpjXdgugA
        - name: fields
          in: query
          required: false
          schema:
            type: string
            description: Used to specify the specific fields you want from the response.
          example: name,statistics.viewCount
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
                  description:
                    type: string
                  publishedAt:
                    type: string
                  thumbnail:
                    type: string
                  url:
                    type: string
                  creatorName:
                    type: string
                  statistics:
                    type: object
                    properties:
                      viewCount:
                        type: integer
                      likeCouunt:
                        type: integer
                      commentCount:
                        type: integer
components:
  securitySchemes:
    apiKey:
      type: apiKey
      in: query
      name: key
